#!/bin/bash
B2_EXT_VER=$1

mkdir /tmp/overlay
mount -t tmpfs tmpfs /tmp/overlay
mkdir /tmp/overlay/{up,work}
mount -t overlay overlay -o\
lowerdir=/b2-ext-mnt,\
upperdir=/tmp/overlay/up,\
workdir=/tmp/overlay/work \
/b2-ext

# userxattr,\
# uuid=on,\

cd /b2-ext-repo
git checkout "$B2_EXT_VER"
cd /
cp -r /b2-ext-repo/* /b2-ext

