CREATE TABLE IF NOT EXISTS event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    t FLOAT
);

CREATE TABLE IF NOT EXISTS fitAndStore (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ptype TEXT,
    t FLOAT,
    event INTEGER NOT NULL,
    FOREIGN KEY (event) REFERENCES event(id)
);

CREATE TABLE IF NOT EXISTS vertexFit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    t FLOAT,
    fitAndStore INTEGER NOT NULL,
    FOREIGN KEY (fitAndStore) REFERENCES fitAndStore(id)
);

CREATE TABLE IF NOT EXISTS fitGFRaveVertex (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    t FLOAT,
    vertexFit INTEGER NOT NULL,
    FOREIGN KEY (vertexFit) REFERENCES vertexFit(id)
);

CREATE TABLE IF NOT EXISTS removeHitsAndRefit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    t FLOAT,
    fitAndStore INTEGER NOT NULL,   
    FOREIGN KEY (fitAndStore) REFERENCES fitAndStore(id)
);
